### ISSUE TITLE
Error when trying to run pine.py

### ISSUE THREAD

**Issue by asseater12** [petercunha/Pine#22]
C:\>python C:\PineBOT\Pine-master\pine.py
Traceback (most recent call last):
  File "C:\PineBOT\Pine-master\pine.py", line 1, in <module>
    from lib import pine
  File "C:\PineBOT\Pine-master\lib\pine.py", line 2, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by wau** [comment]
try 
> pip install termcolor

**Comment by FidgetySo** [comment]
In console pip install termcolor

**Comment by MarcelodeFA** [comment]
![image](https://user-images.githubusercontent.com/85201643/123222444-56bfc480-d4a6-11eb-8636-a91d5c3b9440.png)
It didnt resolve

**Comment by MarcelodeFA** [comment]
> In console pip install termcolor

![image](https://user-images.githubusercontent.com/85201643/123222538-6c34ee80-d4a6-11eb-85b6-67ed4c280c5a.png)
Always the same error

**Comment by MarcelodeFA** [comment]
I uninstalled it and reinstalled, ir worked for me.
