### ISSUE TITLE
I cant open pine.py

### ISSUE THREAD

**Issue by tsety** [petercunha/Pine#30]
when i put "pip install win32gui" in the cmd running in the main directory it come with this error
-
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\admin\AppData\Local\Temp\tmp1amgpa5u'
       cwd: C:\Users\admin\AppData\Local\Temp\pip-install-usxzf9wp\win32gui
  Complete output (20 lines):
  Traceback (most recent call last):
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-jufqitua\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-jufqitua\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-jufqitua\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\admin\AppData\Local\Temp\pip-build-env-jufqitua\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 27, in <module>
      from win32.distutils.gui import win32gui_build_ext
    File "C:\Users\admin\AppData\Local\Temp\pip-install-usxzf9wp\win32gui\win32\distutils\gui.py", line 6, in <module>
      from .command import win32_build_ext
  ModuleNotFoundError: No module named 'win32.distutils.command'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\admin\AppData\Local\Temp\tmp1amgpa5u' Check the logs for full command output.
-
someone help i have been stuck on this for a while

**Comment by chrisovato** [comment]
What did you do to solve it?
