### ISSUE TITLE
Can't find labels path

### ISSUE THREAD

**Issue by ray-kord** [petercunha/Pine#52]
I'm unable to run the program due to it not being able to find the labels. Am I missing something

====================================
 Pine: Neural-Network Aimbot (v0.1)
====================================

[INFO] press '0' to quit or ctrl+C in console...
Traceback (most recent call last):
  File "C:\Users\User\Documents\Pine-master\pine.py", line 14, in <module>
    pine.start(ENABLE_AIMBOT=True)
  File "C:\Users\User\Documents\Pine-master\lib\pine.py", line 74, in start
    LABELS = open(labelsPath).read().strip().split("\n")
FileNotFoundError: [Errno 2] No such file or directory: '\\models\\coco-dataset.labels'
[Finished in 0.405s]

**Comment by miguel-leal** [comment]
seems like is missing this file <coco-dataset.labels> on models folder
