### ISSUE TITLE
Script not working 

### ISSUE THREAD

**Issue by CrabotY** [petercunha/Pine#59]
On startup it gives the following error.

====================================
 Pine: Neural-Network Aimbot (v0.1)
====================================

[INFO] press '0' to quit or ctrl+C in console...
[INFO] loading neural-network from disk...
Traceback (most recent call last):
  File "d:\Desktop\Pine-master\pine.py", line 14, in <module>
    pine.start(ENABLE_AIMBOT=True)
  File "d:\Desktop\Pine-master\lib\pine.py", line 95, in start
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "d:\Робочий стол\Pine-master\lib\pine.py", line 95, in <listcomp>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

**Comment by Allmight0000** [comment]
I have the same error, did you manage to solve it?

**Comment by jake4653** [comment]
I found the fix

**Comment by jake4653** [comment]
in line 95 in the pine.py in the lib folder replace that line with          ln = [ln[i - 1] for i in net.getUnconnectedOutLayers()]

**Comment by jake4653** [comment]
ln = [ln[i - 1] for i in net.getUnconnectedOutLayers()]

**Comment by jake4653** [comment]
small mistake but easy fix replacing [0] with i
