### ISSUE TITLE
get an error

### ISSUE THREAD

**Issue by kelopuu** [petercunha/Pine#60]
Traceback (most recent call last):
  File "C:\Users\kelot\Downloads\Pine-master\Pine-master\pine.py", line 14, in <module>
    pine.start(ENABLE_AIMBOT=True)
  File "C:\Users\kelot\Downloads\Pine-master\Pine-master\lib\pine.py", line 95, in start
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kelot\Downloads\Pine-master\Pine-master\lib\pine.py", line 95, in <listcomp>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
             ~^^^
IndexError: invalid index to scalar variable.

**Comment by ghost** [comment]
same

**Comment by zyklone4096** [comment]
+1

**Comment by sean05112142** [comment]
for me it worked to modify this line

ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]

to this

ln = [ln[i - 1] for i in net.getUnconnectedOutLayers()]
